Description of qp_ca_sl
qp_ca_sl
PURPOSE
Wrapper used in the QP control allocation Simulink block.
SYNOPSIS
function u = qp_ca_sl(arg,B,plim,rlim,T,Wv,Wu,ud,alg,imax,gam,tol)
DESCRIPTION
 Wrapper used in the QP control allocation Simulink block.
CROSS-REFERENCE INFORMATION
This function calls:
cgi_alloc CGI_ALLOC - Control allocation based on cascading generalized inverses.
fxp_alloc FXP_ALLOC - Control allocation using a fixed-point iterations.
ip_alloc IP_ALLOC - Control allocation using interior point method.
mls_alloc MLS_ALLOC - Control allocation using minimal least squares.
sls_alloc SLS_ALLOC - Control allocation using sequential least squares.
wls_alloc WLS_ALLOC - Control allocation using weighted least squares.
wlsc_alloc WLSC_ALLOC - C implementation of WLS_ALLOC.
This function is called by:
SOURCE CODE
function u = qp_ca_sl(arg,B,plim,rlim,T,Wv,Wu,ud,alg,imax,gam,tol)
% Wrapper used in the QP control allocation Simulink block.
% Dimensions
  [k,m] = size(B);
  % Extract nonconstant input arguments
  v = arg(1:k);
  uprev = arg(k+1:end);
  % Overall position limits
  if isempty(rlim)
    umin = plim(:,1);
    umax = plim(:,2);
  else
    umin = max(plim(:,1),uprev+rlim(:,1)*T);
    umax = min(plim(:,2),uprev+rlim(:,2)*T);
  end
  u0 = mean([umin umax]')';
  W0 = zeros(m,1);
  switch lower(alg)
   case 'sls'
    u = sls_alloc(B+j,v,umin,umax,Wv,Wu,ud,u0,W0,imax);
   case 'mls'
    u =    mls_alloc(B,v,umin,umax,Wv,Wu,ud,u0,W0,imax);
   case 'wls'
    u = wls_alloc(B,v,umin,umax,Wv,Wu,ud,gam,u0,W0,imax);
   case 'wlsc'
    u = wlsc_alloc(B,v,umin,umax,Wv,Wu,ud,gam,u0,W0,imax);
   case 'ip'
    u = ip_alloc(B,v,umin,umax,ud,gam,tol,imax);
   case 'fxp'
    u = fxp_alloc(B,v,umin,umax,Wv,Wu,ud,gam,u0,imax);
   case 'cgi'
    u = cgi_alloc(B,v,umin,umax,Wv,Wu,ud);
  end