function [fitresult, gof] = createFit(M_eval, H_eval, alpha_map)
%CREATEFIT(M_EVAL,H_EVAL,ALPHA_MAP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : M_eval
%      Y Input : H_eval
%      Z Output: alpha_map
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jul-2014 12:45:21


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( M_eval, H_eval, alpha_map );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'alpha_map vs. M_eval, H_eval', 'Location', 'NorthEast' );
% Label axes
xlabel( 'M_eval' );
ylabel( 'H_eval' );
zlabel( 'alpha_map' );
grid on
view( 177.5, 54 );


