function [fitresult, gof] = Interpolate_FE(XX, YY, ZZ)
%CREATEFIT(XX,YY,ZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : XX
%      Y Input : YY
%      Z Output: ZZ
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2014 00:26:29


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( XX, YY, ZZ );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'ZZ vs. XX, YY', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XX' );
ylabel( 'YY' );
zlabel( 'ZZ' );
grid on
view( -16.5, 80 );


