function [fitresult, gof] = createFit_2(M_eval, H_eval, alpha_map_eval)
%CREATEFIT1(M_EVAL,H_EVAL,ALPHA_MAP_EVAL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : M_eval
%      Y Input : H_eval
%      Z Output: alpha_map_eval
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jul-2014 16:10:41


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( M_eval, H_eval, alpha_map_eval );

% Set up fittype and options.
ft = fittype( 'poly44' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'alpha_map_eval vs. M_eval, H_eval', 'Location', 'NorthEast' );
% Label axes
xlabel( 'M_eval' );
ylabel( 'H_eval' );
zlabel( 'alpha_map_eval' );
grid on
view( -2.5, 52 );


