function [fitresult, gof] = Exp_fit(time_fit, p_fit)
%CREATEFIT(TIME_FIT,P_FIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time_fit
%      Y Output: p_fit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jul-2014 17:57:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time_fit, p_fit );

% Set up fittype and options.
ft = fittype( 'a + b*exp(-tau*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.8002804688888 0.141886338627215 0.421761282626275];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'p_fit vs. time_fit', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'time_fit' );
ylabel( 'p_fit' );
grid on


