function [fitresult, gof] = createFit1(M_eval_sche, H_eval_sche, ZZ)
%CREATEFIT1(M_EVAL_SCHE,H_EVAL_SCHE,ZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : M_eval_sche
%      Y Input : H_eval_sche
%      Z Output: ZZ
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jul-2014 16:20:35


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( M_eval_sche, H_eval_sche, ZZ );

% Set up fittype and options.
ft = fittype( 'loess' );
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'ZZ vs. M_eval_sche, H_eval_sche', 'Location', 'NorthEast' );
% Label axes
xlabel( 'M_eval_sche' );
ylabel( 'H_eval_sche' );
zlabel( 'ZZ' );
grid on
view( -16.5, 52 );


